### ISSUE TITLE
Could not install from npm

### ISSUE THREAD

**Issue by dwiyatci** [cerebral/cerebral-view-angular2#1]
It seems like 'cerebral-view-angular2' is not in the npm registry yet?

https://www.npmjs.com/search?q=cerebral-view-angular2

**Comment by christianalfoni** [comment]
Its being worked on :-)

**Comment by dwiyatci** [comment]
Will patiently be waiting... :grin:

**Comment by rodamora** [comment]
Package is published on npm. Enjoy!

**Comment by dwiyatci** [comment]
Thanks for the effort, guys! :beers:
